### PR TITLE
Added object type to options

### PR DESCRIPTION
**Pull request by RichardLitt**
Not realizing that token needed to be in an `{token: 'string}` form threw me. This should help.

### CODE REVIEW

**Comment by SamVerschueren** [comment]
As @kevva has other priorities at the moment I have to decide that I'm going to pass on this. This is how we document all of our APIs.

**Comment by RichardLitt** [comment]
Fair enough. It might be worth actually going through and updating your other APIs, though, as the current setup can be confusing. Granted, I have no idea how many APIs you have.

**Comment by SamVerschueren** [comment]
It's not only me though, it's also @kevva and @sindresorhus who do it in the exact same way. So yes, it's quite a lot of repositories ;). I never saw someone complaining about the current structure. We experimented with a TypeScript/Flow like approach with type information but until now, we still do it this way.

**Comment by RichardLitt** [comment]
Cool. Alright! No worries then.

**Pull request closed without merging**
