### PR TITLE
add hightlight forks

### PR DESCRIPTION
**Pull request by saromanov**
Hi!
I've just added highlight forks, when it call from command line

```
github-repositories username -f
```

or

```
github-repositories username --hl-forks
```

After that, all links to forked repositories will be shown with different color (i choose chalk.bold.blue)

### CODE REVIEW

**Comment by sindresorhus** [comment]
Sounds useful, but I don't see the point of having it behind an option. It could just be the default.

**Comment by saromanov** [comment]
@sindresorhus If this will be by default, it need to provide additional note, that colored links is forks. So, it seems to me, that easiest way, just to give this feature by option.

**Comment by sindresorhus** [comment]
"an option" seems to always be the easiest way, but most often not the best. Might be other ways than color to mark something as a fork. Just throwing it out there.

**Comment by saromanov** [comment]
So, no need options, just set it by default?

**Comment by kevva** [comment]
@sindresorhus, what color would fit here? Dunno if I want to highlight forks more than regular repos, rather dim them.

**Comment by sindresorhus** [comment]
> Might be **other ways than color** to mark something as a fork.

Either `chalk.dim()` or `Foo (fork)` (with the parens part dimmed).

**Comment by kevva** [comment]
Alright, I think I'll go with `name (fork)`. Feel free to disagree and change it though ;P.

**Pull request closed without merging**
